name: Generate contribution snake 🐍

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: maimun-hossain
          outputs: |
            dist/github-snake.svg?color_snake=#52c76d&color_dots=#bcd4c4,#2f8f4e,#3eaa5d,#52c76d,#7ddd92
            dist/github-snake-dark.svg?color_snake=#52c76d&color_dots=#bcd4c4,#2f8f4e,#3eaa5d,#52c76d,#7ddd92

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
